POST http://localhost:3001/anari/pelaajat
Content-Type: application/json

{
    "standing": 0,
    "name": "Kivikari",
    "teams": [
        {
            "teamId": 29
        },
        {
            "teamId": 15
        },
        {
            "teamId": 1
        },
        {
            "teamId": 22
        },
        {
            "teamId": 26
        },
        {
            "teamId": 20
        },
        {
            "teamId": 19
        },
        {
            "teamId": 30
        },
        {
            "teamId": 25
        },
        {
            "teamId": 17
        },
        {
            "teamId": 9
        },
        {
            "teamId": 14
        }
    ],
    "points": 0,
    "pisteporssi": 139
}