POST http://localhost:3001/anari/players
Content-Type: application/json

{
    "name": "Kivikari",
    "teams": [
        {
            "teamId": "LAK"
        },
        {
            "teamId": "WSH"
        },
        {
            "teamId": "CBJ"
        },
        {
            "teamId": "TBL"
        },
        {
            "teamId": "DAL"
        },
        {
            "teamId": "DET"
        },
        {
            "teamId": "NJD"
        },
        {
            "teamId": "STL"
        },
        {
            "teamId": "CGY"
        },
        {
            "teamId": "MIN"
        },
        {
            "teamId": "EDM"
        },
        {
            "teamId": "OTT"
        }
    ],
    "points": 0,
    "statLeader": 139
}