PUT http://localhost:3001/anari/players
Content-Type: application/json

{
    "name": "Saku",
    "conference": [
        {"seriesLetter": "M", "topWins": 4, "bottomWins": 1 },
        {"seriesLetter": "N", "topWins": 4, "bottomWins": 3 }
    ]
}