POST http://localhost:3001/anari/pelaajat
Content-Type: application/json

{
    "standing": 0,
    "name": "Järvinen",
    "teams": [
        {
            "teamId": 13
        },
        {
            "teamId": 10
        },
        {
            "teamId": 12
        },
        {
            "teamId": 3
        },
        {
            "teamId": 30
        },
        {
            "teamId": 21
        },
        {
            "teamId": 22
        },
        {
            "teamId": 20
        }
    ],
    "points": 0,
    "pisteporssi": 110
}